- name: Desplegar en ECS
        run: |
          # Esto registra la nueva versión de tu tarea automáticamente
          aws ecs register-task-definition --cli-input-json file://deploy/task-definition.json
          
          # Esto actualiza tu servicio (si no existe, lo crearemos una sola vez)
          aws ecs update-service --cluster cluster-servicios-electricos --service contact-service-run --task-definition contact-service-task --force-new-deployment