- name: Deploy to ECS
        run: |
          # Esto registra la tarea usando el JSON que ya está en tu repositorio
          aws ecs register-task-definition --cli-input-json file://deploy/task-definition.json
          
          # Esto actualiza el servicio para que use la nueva imagen
          aws ecs update-service --cluster cluster-servicios-electricos \
            --service contact-service-run \
            --task-definition contact-service-task \
            --force-new-deployment